 function Comp = addComponents2Panel_LoadImage_Cine(hPanel)

h_Gap = 0.025; 
h_Info = 0.6;

nB = 2;
h_Button = (1-h_Gap*(nB+2)-h_Info)/nB;

BC_PB = [1 1 1]*0.25;

% image info
h = 1-h_Gap-h_Info;
Comp.hPanel.ImageInfo = uipanel('parent', hPanel,...
                                'Unit', 'Normalized',...
                                'Position', [.0, h, 1, h_Info], ...
                                'Title', '',...
                                'FontSize',                 10,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'k',...
                                'ShadowColor',            'k');

nR = 3;
txt.FirstRow = {'Name', 'Value'};
txt.FirstColumn = {'FoV'; 'Image Size'; 'Pixel Size'};
columnRatio = [1]; % width ratio to first column
txt.DataStr = {'350'; ''; ''};
FS = 10;

[Comp.hEdit.ImageInfo] = fun_myTable(Comp.hPanel.ImageInfo, nR, columnRatio, txt, FS, [0 0 0]);

% load image
h = h-h_Gap-h_Button;
Comp.Pushbutton.LoadImage = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Load Cine Series',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 h 0.6 h_Button], ...
                                'FontSize', 12, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_LoadImagePanel_LoadImage_Cine);
                            
% load contour
w_Gap = 0.01; 
nB = 2;
w_B = (1-w_Gap*3)/nB;

h = h-h_Gap-h_Button;
Comp.Pushbutton.LoadContour = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Load Contours',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 h 0.6 h_Button], ...
                                'FontSize', 11, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Enable', 'off', ...
                                'Callback', @Callback_Pushbutton_LoadImagePanel_LoadContour_Cine);

% % tumor detection
% Comp.Pushbutton.DetectTumor = uicontrol('parent', hPanel, ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'Detect Tumor',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [w_Gap*2+w_B h w_B h_Button], ...
%                                 'FontSize', 11, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Callback', @Callback_Pushbutton_LoadImagePanel_DetectTumor);
                            