 function Comp = addComponents2Panel_Point(hPanel)

 h_Gap = 0.05;
 h_Button = 0.125;
 w_Button = 0.7;
 x_Button = (1-w_Button)/2;
 
nG = 3;

w_Button2 = 0.45;
x_Button1 = 0.05;
x_Button2 = 0.5;


FS = 11;
h = 1-h_Gap-h_Button;
Comp.Text.Neighbour = uicontrol('Parent', hPanel, ...
                                'Style', 'text', ...
                                'Units',                     'normalized', ...
                                'Position', [0.0 h 0.7 h_Button], ...
                                'FontSize', FS, ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', 'c',...
                                'Enable', 'on', ...
                                'Visible', 'on',...
                                'String', 'Neighbour Points');

Comp.Popup.Neighbour = uicontrol('Parent', hPanel, ...
                                'Style', 'popupmenu', ...
                                'Units',                     'normalized', ...
                                'Position', [0.7 h 0.25, h_Button], ...
                                'FontSize', FS, ...
                                'BackgroundColor', 'w',...
                                'ForegroundColor', 'b',...
                                'Visible', 'on',...
                                'Enable', 'off', ...
                                'String', {'0', '1', '2', '3', '4', '5', '6'});

h = h-h_Gap-h_Button;
Comp.Radiobutton.Tumor = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', 'Tumor',...
                                'Unit', 'Normalized',...
                                'Position', [0.1 h 0.35 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Value', 1, ...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Tag', 'Tumor', ...
                                'Callback', @Callback_Radiobutton_PointPanel_);

Comp.Radiobutton.Dome = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', 'Dome',...
                                'Unit', 'Normalized',...
                                'Position', [0.55 h 0.35 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Tag', 'Dome', ...
                                'Callback', @Callback_Radiobutton_PointPanel_);

h = h-h_Gap-h_Button;
Comp.Pushbutton.Init = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Initialize Points',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Pushbutton_PointPanel_Init);
                            

h = h-h_Gap-h_Button;
Comp.Togglebutton.Move = uicontrol('parent', hPanel, ...
                                'Style', 'Togglebutton',...
                                'String', 'Move Points',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.75 ,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Togglebutton_PointPanel_Move);

h = h-h_Gap*2-h_Button;
Comp.Pushbutton.PointPlot = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Mesurement Plot',...
                                'Unit', 'Normalized',...
                                'Position', [0.1 h 0.8 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Pushbutton_PointPanel_MeasurementPlot);
                            
h = h-h_Gap-h_Button;
Comp.Pushbutton.SavePoint = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', '',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'off', ...
                                'Enable', 'off', ...
                                'Callback', @a);
                            
