 function Comp = addComponents2Panel_Measure_Cine(hPanel)

 nButton = 3;
 h_Gap = 0.025;
 h_Button = (1-h_Gap*(nButton+1))/nButton;
 w_Button = 0.35;
 x_Button = h_Gap;
 
FS = 11;

str{1} = 'Wave';
str{2} = 'Distance';
str{3} = '';

y = 1;
for n = 1:2%nButton
    y = y - h_Gap-h_Button;
    Comp.Radiobutton.Measure_Cine(n) = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', str{n},...
                                'Unit', 'Normalized',...
                                'Position', [x_Button y w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Value', 0, ...
                                'Visible', 'on', ...
                                'Tag', str{n}, ...
                                'Callback', @Callback_Radiobutton_Measure_Cine_);
    y_Button(n) = y;
end

Comp.Radiobutton.Measure_Cine(2).Enable = 'off';

w_Text = 0.3;
 x_Text = w_Button + h_Gap*5;
 
 x_Edit = w_Button + w_Text + h_Gap*6;
 w_Edit = (1-x_Edit) - h_Gap;
 
 Comp.Text.NoP = uicontrol('parent', hPanel, ...
                                'Style', 'text',...
                                'String', 'Avg. Points on each side',...
                                'Unit', 'Normalized',...
                                'Position', [x_Text y_Button(1) w_Text h_Button], ...
                                'HorizontalAlignment', 'center', ...
                                'FontSize', 9, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', 'w',...
                                'Visible', 'on');
                            
 Comp.Edit.NoP = uicontrol('parent', hPanel, ...
                                'Style', 'edit',...
                                'Unit', 'Normalized',...
                                'Position', [x_Edit y_Button(1) w_Edit h_Button],...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', 'g',...
                                'String', '10', ...
                                'Visible', 'on', ...
                                'Callback', @Callback_Cine_Edit_Measure_NoP);
