 function Comp = addComponents2Panel_Cine_LoadImage(hPanel)

h_Gap = 0.05; 
nB = 2;
h_Button = (1-h_Gap*(nB+2))/nB;

BC_PB = [1 1 1]*0.25;

% load image
y = 1-h_Gap-h_Button;
Comp.Pushbutton.LoadImage = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Load Cine Series',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 y 0.6 h_Button], ...
                                'FontSize', 12, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Cine_Pushbutton_LoadImagePanel_LoadImage);
                            
% load contour
y = y-h_Gap-h_Button;
Comp.Pushbutton.LoadContour = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Load Contours',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 y 0.6 h_Button], ...
                                'FontSize', 11, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Enable', 'off', ...
                                'Callback', @Callback_Cine_Pushbutton_LoadImagePanel_LoadContour);