 function Comp = addComponents2Panel_Measure_Cine(hPanel)

 nButton = 3;
 h_Gap = 0.05;
 h_Button = (1-h_Gap*(nButton+1))/nButton;
 w_Button = 0.5;
 x_Button = (1-w_Button)/2;
 
FS = 11;

str{1} = 'Wave';
str{2} = 'Distance';
str{3} = '';

y = 1;
for n = 1:2%nButton
    y = y - h_Gap-h_Button;
    Comp.Radiobutton.Measure_Cine(n) = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', str{n},...
                                'Unit', 'Normalized',...
                                'Position', [x_Button y w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Value', 0, ...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Tag', str{n}, ...
                                'Callback', @Callback_Radiobutton_Measure_Cine_);
end