 function Comp = addComponents2Panel_Cine_PtInfo(hPanel)

h_Gap = 0.05; 
nB = 2;
h_Button = (1-h_Gap*(nB+2))/nB;

BC_PB = [1 1 1]*0.25;

y = 1-h_Gap-h_Button;
Comp.Text.PtInfo = uicontrol('parent', hPanel, ...
                                'Style', 'Text',...
                                'String', 'MRN                ',...
                                'Unit', 'Normalized',...
                                'Position', [0.1 y 0.8 h_Button], ...
                                'FontSize', 12, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', 'c',...
                                'Visible', 'on');
                           