 function Comp = addComponents2Panel2_Button1(hPanel)

 nB = 4;
 h_Gap = 0.05;
 h_Button = (1-h_Gap*(nB+1))/nB;
 w_Button = 0.8;
 x_Button = (1-w_Button)/2;

BC =  [1 1 1]*0.25;
FS = 11;
h = 1-h_Gap-h_Button;
Comp.Radiobutton.xt = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', 'X-Tumor',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC,...
                                'ForegroundColor', 'b',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Radiobutton_Button1Panel);
                            
h = h-h_Gap-h_Button;
Comp.Radiobutton.yt = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', 'Y-Tumor',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Tag', 'hProfile', ...
                                'Callback', @Callback_Radiobutton_Button1Panel);

h = h-h_Gap-h_Button;
Comp.Radiobutton.xd = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', 'X-Diaphragm',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC,...
                                'ForegroundColor', 'y',...
                                'Visible', 'on', ...
                                'Tag', 'vProfile', ...
                                'Callback', @Callback_Radiobutton_Button1Panel);
                            
h = h-h_Gap-h_Button;
Comp.Radiobutton.yd = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', 'Y-Diaphragm',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC,...
                                'ForegroundColor', 'g',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Radiobutton_Button1Panel);                            