function Comp = addComponents2Panel_ZoomButton(hPanel, TagNo)

BC_PB = [1 1 1]*0.25;

Comp.Pushbutton.Zoom = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'O',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 0.2 0.6 0.6], ...
                                'FontSize', 12, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Tag', num2str(TagNo), ...
                                'Callback', @Callback_Pushbutton_ZoomButton_);
                            
% Comp.hZoom.Slice = uicontrol('Parent',  hPanel,...
%             'Style','Pushbutton',...
%             'Units', 'normalized',...
%             'Position',[0.2 0.1 0.6 0.8],...
%             'BackgroundColor', 'b',...
%             'ForegroundColor', 'w',...
%             'Visible', 'on', ...
%                 'Callback', @Callback_Slider_SliceSliderPanel_SliceSlider);
%             
% Comp.hText.nImages = uicontrol('Parent', hPanel, ...
%                                 'Style', 'text', ...
%                                 'Units',                     'normalized', ...
%                                 'Position', [0. 0.025 1 0.05], ...
%                                 'FontSize', 12, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', 'b',...
%                                 'ForegroundColor', 'w',...
%                                 'Visible', 'on', ...
%                                 'String', 'iSlice / nSlices');