function Comp = addComponents2Panel_Table_Table(hPanel)

nButton = 5;
h_Gap = 0.025*ones(nButton+1, 1);
h_Gap (4) = h_Gap(1)*2;
h_Gap(end-1) = h_Gap(4);
h_Button = (1-sum(h_Gap))/nButton;
w_Button = 0.8*ones(nButton, 1);
w_Button(1) = 0.4;
w_Gap = (1-w_Button(end))/2;

FS = 11;

str{1} = 'New';
str{2} = 'Load Data';
str{3} = 'Save Data';
str{4} = 'Threshold';
str{5} = 'Incert CT_Tx';

y = 1;
for n = 1:nButton
    y = y - h_Gap(n)-h_Button;
    Comp.Pushbutton(n) = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', str{n},...
                                'Unit', 'Normalized',...
                                'Position', [w_Gap y w_Button(n) h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Value', 0, ...
                                'Visible', 'on', ...
                                'Tag', str{n}, ...
                                'Callback', @Callback_Table_Pushbutton_);
    y_Button(n) = y;
end

Comp.PopUp = uicontrol('parent', hPanel,...
                                    'Style',  'popupmenu',...
                                    'Units',                          'normalized', ...
                                    'Position',                      [0.6 y_Button(1) 0.3 h_Button],...
                                    'ForegroundColor',         [1 1 1],...
                                     'BackgroundColor',         [0 0 0],...
                                    'FontSize',                     12, ...
                                    'FontWeight', 'bold', ...
                                    'String', {'MRI', 'CT'}, ...
                                    'Callback', @Callback_Table_Popup);
