 function Comp = addComponents2Panel_Selection(hPanel)

 nButton = 2;
 h_Gap = 0.05;
 h_Button = (1-h_Gap*(nButton+1))/nButton;
 w_Button = 0.5;
 x_Button = (1-w_Button)/2;
 
nG = 3;
FS = 11;

y = 1-h_Gap-h_Button;
Comp.Radiobutton.Diaphragm = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', 'Diaphragm',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button y w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Value', 1, ...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Tag', 'Diaphragm', ...
                                'Callback', @Callback_Radiobutton_SelectionPanel_);

y = y-h_Gap-h_Button;
Comp.Radiobutton.Body = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', 'Abdomen',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button y w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Tag', 'Body', ...
                                'Callback', @Callback_Radiobutton_SelectionPanel_);