 function Comp = addComponents2Panel_Tumor(hPanel)

 h_Gap = 0.1;
 h_Button = 0.6;
 w_Button = 0.8;
 x_Button = (1-w_Button)/2;
 
nG = 3;

w_Button2 = 0.4;
x_Button1 = 0.05;
x_Button2 = 0.5;

FS = 11;
BC_PB = [1 1 1]*0.25;
BC_TB = [1 1 1]*0.75;

h = 1-h_Gap-h_Button;
Comp.Pushbutton.Init = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Initilize Profile',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Pushbutton_TumorPanel_Init);