 function Comp = addComponents2Panel2_Button(hPanel)

 nB = 5;
 h_Gap = 0.05;
 h_Button = (1-h_Gap*(nB+1))/nB;
 w_Button = 0.8;
 x_Button = (1-w_Button)/2;

BC =  [1 1 1]*0.25;
FS = 11;
h = 1-h_Gap-h_Button;
Comp.Radiobutton.bwSum = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', 'bwSum',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Radiobutton_ButtonPanel_bwSum);

h = h-h_Gap-h_Button;
Comp.Radiobutton.Contour = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', 'Contour',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Radiobutton_ButtonPanel_Contour);
                            
h = h-h_Gap-h_Button;
Comp.Pushbutton.hProfile = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'hProfile',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Tag', 'hProfile', ...
                                'Callback', @Callback_Pushbutton_ButtonPanel_vProfile);

h = h-h_Gap-h_Button;
Comp.Pushbutton.vProfile = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'vProfile',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Tag', 'vProfile', ...
                                'Callback', @Callback_Pushbutton_ButtonPanel_vProfile);

                            
h = h-h_Gap-h_Button;
Comp.Pushbutton.SaveMeasureData = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Save Data',...
                                'Unit', 'Normalized',...
                                'Position', [x_Button h w_Button h_Button], ...
                                'FontSize', FS+2, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC,...
                                'ForegroundColor', 'w',...
                                'Visible', 'on', ...
                                'Tag', 'SaveMeasureData', ...
                                'Callback', @Callback_Pushbutton_ButtonPanel_SaveMeasureData);