function subPanel = addComponents2Panel_Cine_View(hPanel, fileList)

FC = [255 255 102]/255;


%% sag, cor, sag+cor
% if numel(fileList) == 3 
    x = [0 0.5 0];
    y = [0.5 0.5 0];
    w = [.5 .5 1];
    h = .5;
    
    sphc = 'b';
    TT{1} = 'Sagittal';
    TT{2} = 'Coronal';
    TT{3} = 'Sag+Cor';
    for n = 1:3
        subPanel(n).hPanel = uipanel('parent', hPanel,...
                                'Unit', 'Normalized',...
                                'Position', [x(n) y(n) w(n) h], ...
                                'Title', TT{n}, ...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'c',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k', ...
                                'Tag', num2str(n));
        
        xx = [.9 0 0 .9];
        yy = [.9 .9 0 0 ];
        ww = [.1 .9 .9 .1];
        hh = [.1 .1 .9 .9];
        for m = 1:4
            subPanel(n).ssPanel(m).hPanel = uipanel('parent', subPanel(n).hPanel,...
                                'Unit', 'Normalized',...
                                'Position', [xx(m) yy(m) ww(m) hh(m)], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          sphc,...
                                'ShadowColor',            'k');
        end
        subPanel(n).ssPanel(4).Comp =...
                 addComponents2Panel_Cine_SliceSlider(subPanel(n).ssPanel(4).hPanel, n);
        subPanel(n).ssPanel(2).Comp =...
                 addComponents2Panel_Cine_ContrastBar(subPanel(n).ssPanel(2).hPanel, n);
        subPanel(n).ssPanel(1).Comp =...
                 addComponents2Panel_Cine_ZoomButton(subPanel(n).ssPanel(1).hPanel, n);
             
        subPanel(n).ssPanel(3).Comp =...
                 addComponents2Panel_View(subPanel(n).ssPanel(3).hPanel);
    end
% end
                            
%                             
%     Comp.hAxis.Image = axes('Parent',                   hPanel, ...
%                             'color',        'none',...
%                             'xcolor', FC,...
%                             'ycolor', FC, ...
%                             'gridcolor',   FC,...
%                             'Units',                    'normalized', ...
%                             'HandleVisibility',     'callback', ...
%                             'Position',                 [0.05 0.025 0.9 0.9]);
% 
% Comp.hAxis.Image.XAxisLocation='top';
% hold(Comp.hAxis.Image, 'on')