function [hMenu, hMenuItem] = addMenu(hFig_main)

%% File
hMenu.File = uimenu('Parent',                 hFig_main,...
                    'HandleVisibility',      'off', ...
                    'Visible', 'off', ...
                    'Label',                     'File');

hMenuItem.ImageInfo  =   uimenu('Parent',               hMenu.File,...
                                'Label',                'Image Info',...
                                    'Checked',           'on',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @Callback_hMenuItem_ImageInfo);
                
hMenuItem.LoadImages  =   uimenu('Parent',               hMenu.File,...
                                'Label',                'Load Images',...
                                    'Checked',           'off',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_LoadImages_Callback);
                            
hMenuItem.LoadSnakes  =   uimenu('Parent',               hMenu.File,...
                                'Label',                'Load Snakes',...
                                    'Checked',           'off',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_LoadSnakes_Callback);
                            
hMenuItem.SaveSnakes  =   uimenu('Parent',               hMenu.File,...
                                'Label',                'Save Snakes',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_SaveSnakes_Callback);

%% Mode
hMenu.Mode = uimenu('Parent',                 hFig_main,...
                    'HandleVisibility',      'off', ...
                    'Label',                     'Mode');
                                            
hMenuItem.MRISim  =   uimenu('Parent',               hMenu.Mode,...
                                'Label',                'MRI_Sim',...
                                    'Checked',           'on',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @Callback_hMenuItem_MRISim);
                            
hMenuItem.Ethos  =   uimenu('Parent',               hMenu.Mode,...
                                'Label',                'Ethos',...
                                    'Checked',           'off',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @Callback_hMenuItem_Ethos);
                            
hMenuItem.ViewRay  =   uimenu('Parent',               hMenu.Mode,...
                                'Label',                'ViewRay',...
                                    'Checked',           'off',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @Callback_hMenuItem_ViewRay);
                            
%% Help                            
hMenu.Help = uimenu('Parent',                 hFig_main,...
                    'HandleVisibility',      'off', ...
                    'Label',                     'Help');
                                            
hMenuItem.Help.About  =   uimenu('Parent',               hMenu.Help,...
                                'Label',                'About MAXIM',...
                                    'Checked',           'off',...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @Callback_hMenuItem_Help_About);
                            
                            
