function addMenu_Ethos_Tx(hFig)

%% File
hMenu.New = uimenu('Parent',                 hFig,...
                    'HandleVisibility',      'on', ...
                    'Visible', 'on', ...
                    'Label',   'New CBCT', ...
                    'Callback', @Callback_Ethos_Tx_MenuItem_New_);

hMenu.Save = uimenu('Parent',                 hFig,...
                    'HandleVisibility',      'on', ...
                    'Visible', 'on', ...
                    'Label',   'Save', ...
                    'Callback', @Callback_Ethos_Tx_MenuItem_Save_);