function Panel = addPanel_Cine(hFig)

h_LoadImage = 0.25;
h_Selection = 0.05;
h_Snake = 0.35;
h_Point = 0.3;
h_About = 1-h_LoadImage-h_Snake-h_Point-h_Selection;

w_Left = 0.2;
w_Right = 0.05;
w_Middle = 1-w_Right-w_Left;

h_ContrastBar = 0.05;
h_View = 1-h_ContrastBar;

%% View
Panel.View.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [w_Left, 0, w_Middle+w_Right, 1], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');


%% Load image
Panel.LoadImage.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 1-h_LoadImage, w_Left, h_LoadImage], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

%% cine overlap view
h_OLView = 0.15;
Panel.OLView.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 1-h_LoadImage-h_OLView, w_Left, h_OLView], ...
                                'Title', 'Contour Overlap',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

%% cine measure view
h_Measure = 0.15;
Panel.Measure.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 1-h_LoadImage-h_OLView-h_Measure, w_Left, h_Measure], ...
                                'Title', 'Measurement',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

%% cine mri/cbct panel
h_mri = 0.15;
Panel.MCI.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 1-h_LoadImage-h_OLView-h_Measure-h_mri, w_Left, h_mri], ...
                                'Title', 'MRI/CBCT Input',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k'); 