function Panel = addPanel_Cine(hFig)

h_PtInfo = 0.1;
h_LoadImage = 0.15;

w_Left = 0.2;
w_Right = 0.05;
w_Middle = 1-w_Right-w_Left;

%% View
Panel.View.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [w_Left, 0, w_Middle+w_Right, 1], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');


%% Patient Info
Panel.PtInfo.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 1-h_PtInfo, w_Left, h_PtInfo], ...
                                'Title', 'Patient',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'g',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

%% Load image
Panel.LoadImage.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 1-h_PtInfo-h_LoadImage, w_Left, h_LoadImage], ...
                                'Title', 'Data',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'g',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

%% cine overlap view
h_OLView = 0.15;
Panel.OLView.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 1-h_PtInfo-h_LoadImage-h_OLView, w_Left, h_OLView], ...
                                'Title', 'Contour Overlap',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

%% cine measure view
h_Measure = 0.2;
Panel.Measure.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 1-h_PtInfo-h_LoadImage-h_OLView-h_Measure, w_Left, h_Measure], ...
                                'Title', 'Measurement',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');