function Panel = addPanel2(hFig)

w1 = 0.5;
w2 = 1-w1;
h1 = 0.3;
h2 = 1-h1;

%% View
Panel.View.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, h2, 1, h1], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

%% tumor
Panel.Tumor.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 0, w1, h2], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

%% profile
Panel.Profile.hPanel = uipanel('Parent',                    hFig,...    
                                'Title',                        '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [w1, 0,  w2, h2],...
                                    'visible',                      'on', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'black');
                            
%% button for Tumor plot
w3 = 0.075;
h3 = 0.25;
Panel.Button.hPanel = uipanel('Parent',                    hFig,...    
                                'Title',                        '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [w1-w3, 0,  w3, h3],...
                                    'visible',                      'on', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'black');
                            
%% button for point plot
h4 = 0.2;
Panel.Button1.hPanel = uipanel('Parent',                    hFig,...    
                                'Title',                        '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [w1-w3, h2-h4,  w3, h4],...
                                    'visible',                      'on', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'black');                            
                            