function Panel = addPanel_Ethos(hFig)

w_Menu = 0.15;
w_View = 1-w_Menu;

h_PtInfo = 0.2;
h_Table = 0.25;
h_Go = 0.1;
h_WaveBar = 0.1;
h_ParamButton = 0.075;
h_Calib = 0.05;
h_Param = 1-h_PtInfo-h_Go-h_WaveBar-h_ParamButton-h_Calib;

% patient info
y0 = 1-h_PtInfo;
Panel.PtInfo.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, y0, w_Menu, h_PtInfo], ...
                                'Title', 'Patient Info',...
                                'FontSize',                 11,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'b',...
                                'ShadowColor',            'k');
                            
% Table
y0 = y0 - h_Table;
Panel.Data.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, y0, w_Menu, h_Table], ...
                                'Title', 'Data',...
                                'FontSize',                 11,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'b',...
                                'ShadowColor',            'k');
                            
Panel.Table.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [w_Menu, 0, 1-w_Menu, 1], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');
                                                        