function [h] = addSubPanels(hPanel, nR, columnRatio)

junk = 1+sum(columnRatio);
wCell = [1 columnRatio]/junk;
nC = length(columnRatio)+1;
hCell = 1/nR;
junk = cumsum(wCell);
xP = [0 junk(1:end-1)];
yP = hCell*(nR-1):-hCell:0;

for iR = 1:nR
    for iC = 1:nC
        h(iR, iC) = uipanel('parent', hPanel,...
                                'Unit', 'Normalized',...
                                'Position', [xP(iC) yP(iR) wCell(iC) hCell],...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'w',...
                                'ShadowColor',            'k');
    end
end