function createFig_Ethos_Tx

global nEthosTxTable
global hFig
data = guidata(hFig);

% data.Ethos.Panel.Tx.Comp.Pushbutton.Tx(iB)

nEthosTxTable = nEthosTxTable+1;
data.Ethos.TxTable(nEthosTxTable).hFig = figure('MenuBar',            'none', ...
                                                        'Toolbar',              'none', ...
                                                        'Name',                ['CBCT_Tx_Fx', num2str(nEthosTxTable)], ...
                                                        'NumberTitle',      'off', ...
                                                        'Units',                 'normalized',...
                                                        'Position',             [0.2 0.2 0.6 0.6],...
                                                        'Color',                 'black', ...
                                                        'CloseRequestFcn', @figCloseReq_Ethos_TxTable_, ...
                                                        'Visible',               'on',...
                                                        'Tag', num2str(nEthosTxTable));


data.Ethos.TxTable(nEthosTxTable).Comp = addTxTable2Fig(data.Ethos.TxTable(nEthosTxTable).hFig);                                                    
                                                    
data.Ethos.Panel.Tx.Comp.Pushbutton.Tx(nEthosTxTable).Visible = 'on';

guidata(hFig, data);