function fun_myTable_1Col(parent, RowRatio, txt, FS)

junk = 1+sum(RowRatio);
hCell = [1 RowRatio]/junk;
nR = length(RowRatio);
% yP = hCell*nR:-hCell:0;

% all cells
yP = 1;
for iR = 1:nR+1
    yP = yP-hCell(iR);
        hET(iR) = uipanel('parent', parent,...
                                'Unit', 'Normalized',...
                                'Position', [0 yP 1 hCell(iR)],...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'w',...
                                'ShadowColor',            'k');
end

for iR = 1:nR
    uicontrol('parent',  hET(iR+1), ...
                    'Style', 'text',...
                    'String', txt.FirstColumn{iR},...
                    'Unit', 'Normalized',...
                    'Position', [0 0 1 1], ...
                    'FontSize', FS, ...
                    'FontWeight', 'bold', ...
                    'BackgroundColor', 'k',...
                    'ForegroundColor', 'w',...
                    'Visible', 'on');
end